name: disc_resource
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    logger: ^2.3.0
    permission_handler: ^11.3.1
    music_kit:
        git:
            url: https://github.com/HondaYt/flutter_music_kit.git
            path: music_kit
    supabase_flutter: ^2.5.7
    http: ^1.2.1
    sign_in_with_apple: ^6.1.1
    appinio_swiper: ^2.1.1
    crypto: ^3.0.5
    flutter_dotenv: ^5.1.0
    interactive_slider:
        git:
            url: https://github.com/HondaYt/interactive_slider.git
            ref: main
    smooth_corner: ^1.1.0
    flutter_native_splash: ^2.4.1
    flutter_riverpod: ^2.5.1
    text_scroll:
        git:
            url: https://github.com/HondaYt/text_scroll.git
            ref: dev
    go_router: ^14.2.7
    sheet: ^1.0.0
    image_picker: ^1.1.2
    image_cropper: ^8.0.2
    background_fetch: ^1.3.7
    flutter_slidable: ^3.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/

flutter_native_splash:
    image: "assets/splash_logo.png"
    color: "0C0C0C"
